from sqlalchemy.dialects.postgresql import VARCHAR, BIGINT, BOOLEAN, TIMESTAMP, TEXT

list_of_tables = ["async_jobs",
"background_jobs",
"capabilities",
"capability_roles",
"customized_views",
"data_alerts",
"data_alerts_recipients",
"data_connections",
"datasources",
"desktop_reporting",
"domains",
"extracts",
"group_users",
"groups",
"hist_capabilities",
"hist_comments",
"hist_datasources",
"hist_groups",
"hist_projects",
"hist_schedules",
"hist_sites",
"hist_tags",
"hist_tasks",
"hist_users",
"hist_views",
"hist_workbooks",
"historical_disk_usage",
"historical_event_types",
"historical_events",
"http_requests",
"import_mapping_excluded_system_users",
"licensing_roles",
"next_gen_permissions",
"nlp_suggestion_groups",
"permission_reasons",
"permissions_templates",
"projects",
"projects_contents",
"projects_view_option_rights",
"projects_view_options",
"roles",
"schedules",
"sessions",
"site_roles",
"site_saml_users",
"sites",
"subscription_messages",
"subscriptions",
"subscriptions_customized_views",
"subscriptions_views",
"subscriptions_workbooks",
"system_users",
"tags",
"tasks",
"users",
"view_metrics_aggregations",
"views",
"views_stats",
"workbooks"
]

mapping_list_tables = [
        # 0 - async_jobs
        {'id': BIGINT,
        'job_type': VARCHAR(255),
        'success': BOOLEAN,
        'worker': VARCHAR(255),
        'user_id': BIGINT,
        'site_id': BIGINT,
        'notes': VARCHAR(8192),
        'progress': BIGINT,
        'created_at': TIMESTAMP,
        'updated_at': TIMESTAMP,
        'completed_at': TIMESTAMP,
        'detailed_status': VARCHAR(32768),
        'luid': VARCHAR(40)},
        # 1 - background_jobs
        {'id': BIGINT,
        'job_type': VARCHAR(255),
        'progress': BIGINT,
        'args': VARCHAR(4096),
        'notes': VARCHAR(20480),
        'updated_at': TIMESTAMP,
        'created_at': TIMESTAMP,
        'completed_at': TIMESTAMP,
        'started_at': TIMESTAMP,
        'job_name': VARCHAR(255),
        'finish_code': BIGINT,
        'priority': BIGINT,
        'title': VARCHAR(255),
        'created_on_worker': VARCHAR(255),
        'processed_on_worker': VARCHAR(255),
        'link': VARCHAR(255),
        'lock_version': BIGINT,
        'backgrounder_id': VARCHAR(255),
        'serial_collection_id': BIGINT,
        'site_id': BIGINT,
        'subtitle': VARCHAR(255),
        'language': VARCHAR(255),
        'locale': VARCHAR(255),
        'correlation_id': BIGINT,
        'attempts_remaining': BIGINT,
        'luid': VARCHAR(40),
        'job_rank': BIGINT,
        'queue_id': BIGINT,
        'overflow': BOOLEAN,
        'promoted_at': TIMESTAMP,
        'task_id': BIGINT,
        'run_now': BOOLEAN,
        'creator_id': BIGINT},
        # 2 - capabilities
        {'id': BIGINT,
        'name': VARCHAR(40),
        'display_name': VARCHAR(255),
        'display_order':BIGINT},
        # 3 - capability_roles
        {'id':BIGINT,
        'capability_id':BIGINT,
        'role_id':BIGINT},
        # 4 - customized_views
        {'id': BIGINT,
        'name': VARCHAR(255),
        'description': TEXT,
        'view_id': BIGINT,
        'repository_url': VARCHAR(255),
        'created_at': TIMESTAMP,
        'updated_at': TIMESTAMP,
        'creator_id': BIGINT,
        'public': BOOLEAN, 
        'size': BIGINT,
        'site_id': BIGINT,
        'repository_data_id': BIGINT,
        'repository_thumbnail_data_id': BIGINT,
        'url_id': VARCHAR(255),
        'start_view_id': BIGINT,
        'luid': VARCHAR(255),
        'data_id': VARCHAR(50),
        'thumbnail_id': VARCHAR(50),
        'hidden': BOOLEAN,
        'created_by_feature'
        'accessed_at': TIMESTAMP,
        'modified_at': TIMESTAMP},
        # 5 - data_alerts
        {'id': BIGINT,
        'title': VARCHAR(256),
        'creator_id': BIGINT,
        'site_id': BIGINT,
        'workbook_id': BIGINT,
        'view_id': BIGINT,
        'customized_view_id': BIGINT,
        'luid': VARCHAR(255),
        'data_specification': VARCHAR(8192),
        'last_checked': TIMESTAMP,
        'notification_interval_in_minutes': BIGINT,
        'created_at': VARCHAR(255),
        'updated_at': VARCHAR(255),
        'last_edited': VARCHAR(255),
        'suspend_state': BIGINT,
        'failure_count': BIGINT,
        'device_type': BIGINT,
        'public': BOOLEAN},
        # 6 - data_alerts_recipients
        {'id': BIGINT,
        'recipient_id': BIGINT,
        'data_alert_id': BIGINT,
        'recipient_type': VARCHAR(256),
        'last_sent': TIMESTAMP,
        'last_state': BOOLEAN,
        'created_at': TIMESTAMP,
        'updated_at': TIMESTAMP,
        'site_id': BIGINT},
        # 7 - data_connections
        {'id': BIGINT,
        'server': VARCHAR(256),
        'dbclass': VARCHAR(128),
        'port': BIGINT,
        'username': TEXT,
        'password': BOOLEAN,
        'name': VARCHAR(256),
        'dbname': VARCHAR(4096),
        'tablename': VARCHAR(256),
        'owner_type': VARCHAR(256),
        'owner_id': BIGINT,
        'created_at': TIMESTAMP,
        'updated_at': TIMESTAMP,
        'caption': VARCHAR(256),
        'site_id': BIGINT,
        'keychain': VARCHAR(8192), 
        'luid': VARCHAR(256),
        'has_extract': BOOLEAN,
        'datasource_id': BIGINT,
        'db_subclass': VARCHAR(256),
        'authentication': VARCHAR(256),
        'using_remote_query_agent': BOOLEAN,
        'query_tagging_enabled': BOOLEAN,
        'credential_luid': VARCHAR(256),
        'cloud_file_request_url': VARCHAR(256)},
        # 8 - datasources
        {'id': BIGINT,
        'name': VARCHAR(256),
        'repository_url': VARCHAR(256),
        'owner_id': BIGINT,
        'created_at': TIMESTAMP,
        'updated_at': TIMESTAMP,
        'project_id': BIGINT,
        'size': BIGINT,
        'lock_version': BIGINT,
        'state': VARCHAR(32),
        'db_class': VARCHAR(256),
        'db_name': VARCHAR(256),
        'table_name': VARCHAR(256),
        'site_id': BIGINT,
        'revision': VARCHAR(256),
        'repository_data_id': BIGINT,
        'repository_extract_data_id': BIGINT,
        'embedded': VARCHAR(8192),
        'incrementable_extracts': BOOLEAN,
        'refreshable_extracts': BOOLEAN,
        'data_engine_extracts': BOOLEAN,
        'extracts_refreshed_at': TIMESTAMP,
        'first_published_at': TIMESTAMP,
        'connectable': BOOLEAN,
        'is_hierarchical': BOOLEAN,
        'extracts_incremented_at': TIMESTAMP,
        'luid': VARCHAR(256),
        'asset_key_id': BIGINT,
        'document_version': VARCHAR(256),
        'description': VARCHAR(256), 
        'content_version': BIGINT,
        'parent_workbook_id': BIGINT,
        'last_published_at': TIMESTAMP,
        'hidden_name': VARCHAR(256),
        'data_id': VARCHAR(50),
        'reduced_data_id': VARCHAR(50),
        'remote_query_agent_id': BIGINT,
        'using_remote_query_agent': BOOLEAN,
        'is_certified': BOOLEAN,
        'certification_note': VARCHAR(256),
        'certifier_user_id': BIGINT,
        'certifier_details': VARCHAR(256),
        'extract_encryption_state': BIGINT,
        'nlp_setting': VARCHAR(256),
        'extract_creation_pending': BIGINT,
        'parent_type': VARCHAR(256),
        'nlp_setting_new': VARCHAR(256),
        'modified_by_user_id': BIGINT,
        'separated_data_id': VARCHAR(50),
        'tds_luid': VARCHAR(256),
        'ask_data_setting': VARCHAR(256),
        'ask_data_indexing': VARCHAR(256),
        'ask_data_curator_feedback': VARCHAR(256),
        'separated_reduced_data_id': VARCHAR(50),
        'extract_storage_format': BIGINT,
        'ask_data_indexing_new': VARCHAR(256)},
        # 9 - desktop_reporting
        {},
        # 10 - domains
        {},
        # 11 - extracts
        {},
        # 12 - group_users
        {},
        # 13 - groups
        {'id': BIGINT,
        'name': VARCHAR(256),
        'created_at': TIMESTAMP,
        'updated_at': VARCHAR(256),
        'system_': BOOLEAN,
        'owner_id': BIGINT,
        'domain_id': BIGINT,
        'site_id': BIGINT,
        'luid': VARCHAR(256),
        'minimum_site_role': VARCHAR(256),
        'last_synchronized': TIMESTAMP,
        'minimum_site_role_id': BIGINT,
        'grant_license_mode': VARCHAR(20)},
        # 14 - hist_capabilities
        {},
        # 15 - hist_comments
        {},
        # 16 - hist_datasources
        {},
        # 17 - hist_groups
        {},
        # 18 - hist_projects
        {},
        # 19 - hist_schedules
        {},
        # 20 - hist_sites
        {},
        # 21 - hist_tags
        {},
        # 22 - hist_tasks
        {},
        # 23 - hist_users
        {},
        # 24 - hist_views  
        {},
        # 25 - hist_workbooks
        {}, 
        # 26 - historical_disk_usage
        {},
        # 27 - historical_event_types
        {},
        # 28 - historical_events
        {'id': BIGINT,
        'historical_event_type_id': BIGINT,
        'worker': VARCHAR(4096),
        'duration_in_ms': BIGINT,
        'is_failure': BOOLEAN,
        'details': VARCHAR(8192),
        'created_at': TIMESTAMP,
        'hist_actor_user_id': BIGINT,
        'hist_target_user_id': BIGINT,
        'hist_actor_site_id': BIGINT,
        'hist_target_site_id': BIGINT,
        'hist_project_id': BIGINT,
        'hist_workbook_id': BIGINT,
        'hist_view_id': BIGINT,
        'hist_datasource_id': BIGINT,
        'hist_comment_id': BIGINT,
        'hist_tag_id': BIGINT,
        'hist_group_id': BIGINT,
        'hist_licensing_role_id': BIGINT,
        'hist_schedule_id': BIGINT,
        'hist_task_id': BIGINT,
        'hist_data_connection_id': BIGINT, 
        'hist_config_id': BIGINT,
        'hist_capability_id': BIGINT,
        'hist_remote_agent_id': BIGINT,
        'hist_flow_id': BIGINT,
        'hist_data_role_id': BIGINT,
        'hist_database_id': BIGINT,
        'hist_table_id': BIGINT,
        'hist_column_id': BIGINT,
        'hist_metric_id': BIGINT,
        'hist_published_connection_id': BIGINT,
        'hist_collection_id': BIGINT,
        'hist_flow_draft_id': BIGINT,
        'hist_data_quality_indicator_id': BIGINT},
        # 29 - http_requests
        {'id': BIGINT,
        'controller': VARCHAR(4096),
        'action': VARCHAR(256),
        'http_referer': VARCHAR(4096),
        'http_user_agent': VARCHAR(4096),
        'http_request_uri': VARCHAR(4096),
        'remote_ip': VARCHAR(256),
        'created_at': TIMESTAMP,
        'session_id': VARCHAR(256),
        'completed_at': TIMESTAMP,
        'port': BIGINT,
        'user_id': BIGINT,
        'worker':  VARCHAR(256),
        'status': BIGINT,
        'user_cookie':  VARCHAR(256),
        'user_ip':  VARCHAR(256),
        'vizql_session': VARCHAR(4096),
        'site_id': BIGINT,
        'currentsheet': VARCHAR(256),
        'flags_used': BIGINT},
        # 30 - import_mapping_excluded_system_users
        {}, 
        # 31 - licensing_roles
        {},
        # 32 - next_gen_permissions  
        {},
        # 33 - nlp_suggestion_groups
        {},
        # 34 - permission_reasons
        {},
        # 35 - permissions_templates
        {},
        # 36 - projects
        {'id': BIGINT,
        'name': VARCHAR(255),
        'owner_id': BIGINT,
        'created_at': TIMESTAMP,
        'updated_at': TIMESTAMP,
        'state': VARCHAR(32),
        'description': VARCHAR(4096),
        'site_id': BIGINT,
        'special': BIGINT,
        'luid': VARCHAR(255),
        'controlled_permissions_enabled': BOOLEAN,
        'parent_project_id': BIGINT,
        'admin_insights_enabled': BOOLEAN,
        'nested_projects_permissions_included': BOOLEAN,
        'controlling_permissions_project_id': BIGINT,
        'lower_name': VARCHAR(255)},
        # 37 - projects_contents
        {},
        # 38 - projects_view_option_rights
        {},
        # 39 - projects_view_options
        {},
        # 40 - roles
        {},
        # 41 - schedules
        {},
        # 42 - sessions
        {'id': BIGINT,
        'session_id': VARCHAR(256),
        'updated_at': TIMESTAMP,
        'user_id': BIGINT,
        'shared_wg_write': VARCHAR(4096),
        'shared_vizql_write': VARCHAR(4096),
        'site_id': BIGINT,
        'created_at': TIMESTAMP,
        'lock_version': BIGINT,
        'salt': VARCHAR(256),
        'hashed_secret': VARCHAR(256),
        'oauth_state': VARCHAR(4096),
        'initiating_user_id': BIGINT},
        # 43 - site_roles
        {},
        # 44 - site_saml_users
        {},
        # 45 - sites
        {},
        # 46 - subscription_messages
        {},
        # 47 - subscriptions
        {},
        # 48 - subscriptions_customized_views
        {},
        # 49 - subscriptions_views
        {},
        # 50 - subscriptions_workbooks
        {},
        # 51 - system_users
        {'id': BIGINT,
        'name': VARCHAR(256),
        'email': VARCHAR(256),
        'hashed_password': VARCHAR(256),
        'salt': VARCHAR(256),
        'sys': BOOLEAN, 
        'keychain': VARCHAR(8192),
        'domain_id': BIGINT,
        'friendly_name': VARCHAR(256),
        'custom_display_name': BOOLEAN,
        'activation_code': VARCHAR(256),
        'activated_at': TIMESTAMP,
        'state': VARCHAR(256),
        'admin_level': BIGINT,
        'created_at': TIMESTAMP,
        'updated_at': TIMESTAMP,
        'deleted_at': TIMESTAMP,
        'auth_user_id': VARCHAR(256),
        'asset_key_id': BIGINT,
        'lock_version': BIGINT,
        'last_password_update': TIMESTAMP,
        'force_password_update': BOOLEAN,
        'last_failed_login': TIMESTAMP,
        'failed_login_attempts': BIGINT,
        'protected_password': VARCHAR(8192),
        'protected_password_bad_format': BOOLEAN},
        # 52 - tags
        {},
        # 53 - tasks
        {},
        # 54 - users
        {}, 
        # 55 - view_metrics_aggregations
        {},
        # 56 - views
        {'id': BIGINT,
        'name': VARCHAR(256),
        'repository_url': VARCHAR(4096),
        'description': VARCHAR(8192),
        'created_at': TIMESTAMP,
        'locked': BOOLEAN,
        'published': BOOLEAN,
        'read_count': BIGINT,
        'edit_count': BIGINT,
        'datasource_id': BIGINT,
        'workbook_id': BIGINT,
        'index': BIGINT,
        'updated_at': TIMESTAMP,
        'owner_id': BIGINT,
        'fields': VARCHAR(8192),
        'title': VARCHAR(8192),
        'caption': VARCHAR(32768),
        'sheet_id': VARCHAR(256),
        'state': VARCHAR(32),
        'sheettype': VARCHAR(256),
        'site_id': BIGINT,
        'repository_data_id': BIGINT,
        'first_published_at': TIMESTAMP,
        'revision': VARCHAR(256),
        'for_cache_updated_at': TIMESTAMP,
        'luid': VARCHAR(256),
        'thumbnail_id': VARCHAR(50),
        'is_deleted': BOOLEAN},
        # 57 - views_stats
        {},
        # 58 - workbooks
        {'id': BIGINT,
        'name': VARCHAR(256),
        'repository_url': VARCHAR(256),
        'description': VARCHAR(4096),
        'created_at': TIMESTAMP,
        'updated_at': TIMESTAMP,
        'owner_id': BIGINT,
        'project_id': BIGINT,
        'view_count': BIGINT,
        'size': BIGINT,
        'embedded': VARCHAR(32768),
        'thumb_user': BIGINT,
        'refreshable_extracts': BOOLEAN,
        'extracts_refreshed_at': TIMESTAMP,
        'lock_version': BIGINT,
        'state': VARCHAR(256),
        'version': VARCHAR(256),
        'checksum': VARCHAR(256),
        'display_tabs': BOOLEAN,
        'data_engine_extracts': BOOLEAN,
        'incrementable_extracts': BOOLEAN,
        'site_id': BIGINT,
        'revision': VARCHAR(256),
        'repository_data_id': BIGINT,
        'repository_extract_data_id': BIGINT,
        'first_published_at': TIMESTAMP,
        'primary_content_url': VARCHAR(256),
        'share_description': VARCHAR(256),
        'show_toolbar': BOOLEAN,
        'extracts_incremented_at': TIMESTAMP,
        'default_view_index': BIGINT,
        'luid': VARCHAR(256),
        'asset_key_id': BIGINT,
        'document_version': VARCHAR(256),
        'content_version': BIGINT,
        'last_published_at': TIMESTAMP,
        'data_id': VARCHAR(256),
        'reduced_data_id': VARCHAR(256),
        'published_all_sheets': BOOLEAN,
        'extract_encryption_state': BIGINT,
        'extract_creation_pending': BIGINT,
        'is_deleted': BOOLEAN,
        'parent_workbook_id': BIGINT,
        'is_private': BOOLEAN,
        'modified_by_user_id': BIGINT,
        'extract_storage_format': BIGINT}
]
